
GET  http://localhost:5000/api/persons

###

POST   http://localhost:5000/api/persons
Content-Type: application/json

 {
     "id": 0,
    "name": "Nufidat",
    "number": "0499-123456"
}
###
POST   http://localhost:5000/api/persons
Content-Type: application/json

 